apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cronjob-cluster-issuer
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: leandro@spacearena.net
    privateKeySecretRef:
      name: cronjob-cluster-issuer-key
    solvers:
      - http01:
          ingress:
            class: nginx
