apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
  namespace: cronjob
type: Opaque
stringData:
  MONGO_URI: mongodb+srv://<username>:<password>@<cluster>.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0


