name: Build and Push Docker Images

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  REGISTRY: registry.spacearena.net
  IMAGE_API: cronjob-api
  IMAGE_FRONTEND: cronjob-frontend

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.1

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: DockerHub Login
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKERHUB_USER}}
          password: ${{secrets.DOCKERHUB_PWD}}

      - name: Build e Push da API
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/Dockerfile.api
          push: true
          tags: artearenahub/cronjob-api:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build e Push do Frontend
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/Dockerfile.frontend
          push: true
          tags: artearenahub/cronjob-frontend:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
